"""BlobStore Protocol."""
from __future__ import annotations

from typing import Protocol


class BlobStore(Protocol):
    def ensure_bucket(self) -> None: ...
    def upload(self, key: str, data: bytes, content_type: str = "application/octet-stream") -> str: ...
    def download(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def public_url(self, key: str) -> str: ...
