#!/usr/bin/env bash
# apply-from-jumphost.sh — Sync runbook ke jumphost, lalu jalankan terraform apply
#
# Setelah apply berhasil, otomatis generate config/topology.env dari output Terraform.
# File topology.env mendefinisikan layer hosts (controller, worker, data).
#
# Usage:
#   PROJECT_ID=my-project ZONE=asia-southeast1-a SSH_USER=annas \
#     ./gcloud/apply-from-jumphost.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNBOOK_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

PROJECT_ID="${PROJECT_ID:?set PROJECT_ID first}"
REGION="${REGION:-asia-southeast1}"
ZONE="${ZONE:-asia-southeast1-a}"
ADMIN_CIDR="${ADMIN_CIDR:-0.0.0.0/0}"
SSH_USER="${SSH_USER:-$USER}"
JUMPHOST_NAME="${JUMPHOST_NAME:-jumphost}"
REMOTE_DIR="${REMOTE_DIR:-gcp-jumphost-nomad}"

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 1
  fi
}

require gcloud
ACCESS_TOKEN="$(gcloud auth print-access-token)"

# ── Step 1: Sync runbook ke jumphost ─────────────────────────────────────────
echo "=== apply-from-jumphost ==="
echo "[1/3] Syncing runbook to jumphost..."

gcloud compute scp \
  --project="${PROJECT_ID}" \
  --zone="${ZONE}" \
  --recurse \
  "${RUNBOOK_DIR}/." \
  "${JUMPHOST_NAME}:~/${REMOTE_DIR}" \
  --quiet

gcloud compute scp \
  --project="${PROJECT_ID}" \
  --zone="${ZONE}" \
  "${SCRIPT_DIR}/jumphost-terraform-bootstrap.sh" \
  "${JUMPHOST_NAME}:~/jumphost-terraform-bootstrap.sh" \
  --quiet

# ── Step 2: Bootstrap terraform dan run apply ─────────────────────────────────
echo "[2/3] Running terraform apply on jumphost..."

gcloud compute ssh \
  "${JUMPHOST_NAME}" \
  --project="${PROJECT_ID}" \
  --zone="${ZONE}" \
  --quiet \
  --command="bash ~/jumphost-terraform-bootstrap.sh ~/${REMOTE_DIR}"

gcloud compute ssh \
  "${JUMPHOST_NAME}" \
  --project="${PROJECT_ID}" \
  --zone="${ZONE}" \
  --quiet \
  --command="cat > ~/${REMOTE_DIR}/terraform/terraform.auto.tfvars <<EOF
project_id = \"${PROJECT_ID}\"
region     = \"${REGION}\"
zone       = \"${ZONE}\"
admin_cidr = \"${ADMIN_CIDR}\"
ssh_user   = \"${SSH_USER}\"
EOF
TF_VAR_access_token='${ACCESS_TOKEN}' PROJECT_ID='${PROJECT_ID}' REGION='${REGION}' ZONE='${ZONE}' ADMIN_CIDR='${ADMIN_CIDR}' SSH_USER='${SSH_USER}' REMOTE_DIR='${REMOTE_DIR}' bash ~/${REMOTE_DIR}/gcloud/import-existing-state.sh"

gcloud compute ssh \
  "${JUMPHOST_NAME}" \
  --project="${PROJECT_ID}" \
  --zone="${ZONE}" \
  --quiet \
  --command="TF_VAR_access_token='${ACCESS_TOKEN}' terraform -chdir=\$HOME/${REMOTE_DIR}/terraform apply -auto-approve"

# ── Step 3: Generate topology config dari terraform output ────────────────────
echo ""
echo "[3/3] Generating config/topology.env from Terraform outputs..."

# Baca output Terraform dari jumphost (topology sudah ada di outputs.tf)
TF_OUTPUT_JSON="$(gcloud compute ssh \
  "${JUMPHOST_NAME}" \
  --project="${PROJECT_ID}" \
  --zone="${ZONE}" \
  --quiet \
  --command="terraform -chdir=\$HOME/${REMOTE_DIR}/terraform output -json")"

# Parse dan buat topology.env lokal
CONTROLLER_IP="$(echo "${TF_OUTPUT_JSON}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
# controller_ip dari outputs.tf
print(data.get('controller_ip', {}).get('value', '') or
      data.get('jumphost_public_ip', {}).get('value', ''))
")"

WORKER_IP="$(echo "${TF_OUTPUT_JSON}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
print(data.get('worker_ip', {}).get('value', '') or
      data.get('jumphost_public_ip', {}).get('value', ''))
")"

DATA_IP="$(echo "${TF_OUTPUT_JSON}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
print(data.get('data_ip', {}).get('value', '') or
      data.get('jumphost_public_ip', {}).get('value', ''))
")"

NOMAD_PRIVATE="$(echo "${TF_OUTPUT_JSON}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
print(data.get('nomad_private_ip', {}).get('value', ''))
")"

mkdir -p "${RUNBOOK_DIR}/config"
cat >"${RUNBOOK_DIR}/config/topology.env" <<EOF
#!/usr/bin/env bash
# topology.env — GENERATED by apply-from-jumphost.sh pada $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Jangan edit manual — jalankan ulang apply-from-jumphost.sh untuk update.
# File ini di-gitignore; setiap komputer punya versi sendiri.

# ── Layer: controller ─────────────────────────────────────────────────────────
# Services: Nomad (:4646), Consul (:8500), platform-api (:8080)
CONTROLLER_HOST="${CONTROLLER_IP}"

# ── Layer: worker ─────────────────────────────────────────────────────────────
# Services: Firecracker agents, FC pool
WORKER_HOST="${WORKER_IP}"

# ── Layer: data ───────────────────────────────────────────────────────────────
# Services: PostgreSQL (:5432), Redis (:6379), MinIO (:9000/:9001), Jaeger (:16686)
DATA_HOST="${DATA_IP}"

# ── Internal IPs ──────────────────────────────────────────────────────────────
NOMAD_PRIVATE_IP="${NOMAD_PRIVATE}"

# ── Ports ─────────────────────────────────────────────────────────────────────
NOMAD_PORT="\${NOMAD_PORT:-4646}"
CONSUL_PORT="\${CONSUL_PORT:-8500}"
API_PORT="\${API_PORT:-8080}"
MINIO_CONSOLE_PORT="\${MINIO_CONSOLE_PORT:-9001}"
MINIO_API_PORT="\${MINIO_API_PORT:-9000}"
JAEGER_PORT="\${JAEGER_PORT:-16686}"
PG_PORT="\${PG_PORT:-5432}"
REDIS_PORT="\${REDIS_PORT:-6379}"

# ── GCP config ────────────────────────────────────────────────────────────────
PROJECT_ID="${PROJECT_ID}"
ZONE="${ZONE}"
NOMAD_NAME="${NOMAD_NAME:-nomad}"
SSH_USER="${SSH_USER}"
EOF

echo ""
echo "Generated: ${RUNBOOK_DIR}/config/topology.env"
echo ""
echo "  Layer topology:"
echo "    controller: ${CONTROLLER_IP}  (Nomad, Consul, platform-api)"
echo "    worker:     ${WORKER_IP}  (Firecracker)"
echo "    data:       ${DATA_IP}  (PG, Redis, MinIO, Jaeger)"
echo ""
echo "  Next steps:"
echo "    source config/topology.env"
echo "    ./gcloud/deploy-full-stack.sh"
echo "    ./smoke-test.sh"
