#!/usr/bin/env bash
# gen-topology.sh — Generate config/topology.env dari Terraform outputs
#
# Jalankan ini setelah `terraform apply` untuk mengisi IP otomatis ke config.
# File yang dihasilkan di-gitignore; setiap komputer/environment punya file sendiri.
#
# Usage:
#   # Di jumphost (setelah terraform apply):
#   ./gcloud/gen-topology.sh
#
#   # Dari local, pointing ke state tertentu:
#   TF_DIR=./terraform ./gcloud/gen-topology.sh
#
#   # Dry-run (print tanpa tulis):
#   ./gcloud/gen-topology.sh --dry-run

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNBOOK_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TF_DIR="${TF_DIR:-${RUNBOOK_DIR}/terraform}"
OUT_FILE="${RUNBOOK_DIR}/config/topology.env"
DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
  esac
done

# ── Baca Terraform outputs ────────────────────────────────────────────────────
echo "Reading Terraform outputs from: ${TF_DIR}"

if ! command -v terraform >/dev/null 2>&1; then
  echo "ERROR: terraform not found in PATH" >&2
  exit 1
fi

TF_JSON="$(terraform -chdir="${TF_DIR}" output -json 2>/dev/null)"

# Ekstrak nilai — gunakan fallback ke env var jika output tidak ada
_tf_val() {
  local key="$1"
  local fallback="${2:-}"
  echo "${TF_JSON}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
val = data.get('${key}', {}).get('value', '${fallback}')
print(val)
" 2>/dev/null || echo "${fallback}"
}

JUMPHOST_PUBLIC_IP="$(_tf_val jumphost_public_ip '')"
NOMAD_PRIVATE_IP="$(_tf_val nomad_private_ip '')"
CONTROLLER_IP="$(_tf_val controller_ip "${JUMPHOST_PUBLIC_IP}")"
WORKER_IP="$(_tf_val worker_ip "${CONTROLLER_IP}")"
DATA_IP="$(_tf_val data_ip "${CONTROLLER_IP}")"
PROJECT_ID="$(_tf_val project_id "${PROJECT_ID:-}")"
ZONE="$(_tf_val zone "${ZONE:-asia-southeast1-a}")"
NOMAD_NAME="$(_tf_val nomad_name "${NOMAD_NAME:-nomad}")"
SSH_USER="${SSH_USER:-$USER}"

if [[ -z "${CONTROLLER_IP}" ]]; then
  echo "ERROR: Tidak bisa menentukan CONTROLLER_IP dari terraform output." >&2
  echo "  Pastikan 'terraform apply' sudah dijalankan, atau set CONTROLLER_IP secara manual." >&2
  exit 1
fi

# ── Generate file ─────────────────────────────────────────────────────────────
GENERATED="$(cat <<EOF
#!/usr/bin/env bash
# topology.env — GENERATED by gen-topology.sh pada $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Jangan edit manual — jalankan ulang gen-topology.sh untuk update.
# File ini di-gitignore; setiap komputer punya versi sendiri.

# ── Layer: controller ─────────────────────────────────────────────────────────
# Services: Nomad (:4646), Consul (:8500), platform-api (:8080)
CONTROLLER_HOST="${CONTROLLER_IP}"

# ── Layer: worker ─────────────────────────────────────────────────────────────
# Services: Firecracker agents, FC pool
# Single-server: sama dengan controller.
WORKER_HOST="${WORKER_IP}"

# ── Layer: data ───────────────────────────────────────────────────────────────
# Services: PostgreSQL (:5432), Redis (:6379), MinIO (:9000/:9001), Jaeger (:16686)
# Single-server: sama dengan controller.
DATA_HOST="${DATA_IP}"

# ── Internal IPs (akses antar-layer via private network) ─────────────────────
NOMAD_PRIVATE_IP="${NOMAD_PRIVATE_IP}"

# ── Ports ────────────────────────────────────────────────────────────────────
NOMAD_PORT="\${NOMAD_PORT:-4646}"
CONSUL_PORT="\${CONSUL_PORT:-8500}"
API_PORT="\${API_PORT:-8080}"
MINIO_CONSOLE_PORT="\${MINIO_CONSOLE_PORT:-9001}"
MINIO_API_PORT="\${MINIO_API_PORT:-9000}"
JAEGER_PORT="\${JAEGER_PORT:-16686}"
PG_PORT="\${PG_PORT:-5432}"
REDIS_PORT="\${REDIS_PORT:-6379}"

# ── GCP config ────────────────────────────────────────────────────────────────
PROJECT_ID="${PROJECT_ID}"
ZONE="${ZONE}"
NOMAD_NAME="${NOMAD_NAME}"
SSH_USER="${SSH_USER}"
EOF
)"

if [[ "${DRY_RUN}" == "true" ]]; then
  echo "--- DRY RUN: would write to ${OUT_FILE} ---"
  echo "${GENERATED}"
  exit 0
fi

mkdir -p "$(dirname "${OUT_FILE}")"
echo "${GENERATED}" > "${OUT_FILE}"

echo ""
echo "Generated: ${OUT_FILE}"
echo ""
echo "  controller: ${CONTROLLER_IP}  (Nomad, Consul, platform-api)"
echo "  worker:     ${WORKER_IP}  (Firecracker)"
echo "  data:       ${DATA_IP}  (PG, Redis, MinIO, Jaeger)"
echo ""
echo "Source dengan:  source config/topology.env"
