# services/monitoring/docker-compose.yml
services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      SPAN_STORAGE_TYPE: memory
      MEMORY_MAX_TRACES: "100000"
    ports:
      - "16686:16686"   # Jaeger UI — buka di browser
      - "4317:4317"     # OTEL gRPC
      - "4318:4318"     # OTEL HTTP
    networks:
      - platform-net
